/**
 * 指令目录(opcode 库,2026-07-05 作者定义:「能查询都有哪些可用的 opcode」)。
 * canonical v5 作者指令手册:kind / 名 / 参数 / 语义 / 原版 opcode 对照。
 * 条目集合必须与 AUTHOR_COMMAND_V5_KINDS 完全一致，由 EventLibTab.test.tsx 锁定。
 */
import type { AuthorCommandV5 } from '@type-pal/content'

export interface CatalogEntry {
  kind: AuthorCommandV5['kind']
  icon: string
  name: string
  group:
    | '演出/对话'
    | '流程/存档'
    | '队伍/场景'
    | '实体'
    | '世界状态'
    | '音频/战斗配置'
    | '走位/相机'
    | '战斗/商店'
    | '控制流'
  /** 参数名: 说明。 */
  params: [string, string][]
  desc: string
  /** 原版 opcode 对照(无 = clean 新增)。 */
  origin?: string
}

export const COMMAND_CATALOG: CatalogEntry[] = [
  // 演出/对话
  {
    kind: 'dialog',
    icon: '💬',
    name: '对话',
    group: '演出/对话',
    params: [
      ['cue.speaker', '说话人(缺省旁白)'],
      ['cue.rows', '正文行(locale 键或字面量)+ 每行打字速度'],
      ['cue.autoAdvance', '尾停顿自动翻页(ms)'],
      ['cue.cursorFrame', '等键光标形态'],
    ],
    desc: '弹对话框逐字打印,按键翻页。',
    origin: '0xFFFF 文本系',
  },
  {
    kind: 'clearDialog',
    icon: '🧹',
    name: '清对话框',
    group: '演出/对话',
    params: [],
    desc: '立即清掉对话框(含立绘)。',
    origin: '0x05 redrawScreen 语义核',
  },
  {
    kind: 'fade',
    icon: '🌓',
    name: '淡入/淡出',
    group: '演出/对话',
    params: [
      ['dir', 'in 淡入 / out 淡出'],
      ['ms', '时长'],
      ['color', 'black/red(战败红)'],
    ],
    desc: '整屏渐变;演出转场。',
    origin: '0x3A/0x3B 系',
  },
  {
    kind: 'holdScreen',
    icon: '⬛',
    name: '保持黑屏',
    group: '演出/对话',
    params: [
      ['color', '固定 black'],
      ['token', '与恢复画面配对的事务标识'],
    ],
    desc: '持有表现层黑屏，直到同 token 的恢复画面、切场景或脚本收尾。',
    origin: '0x76 持续黑屏语义',
  },
  {
    kind: 'revealScreen',
    icon: '🌅',
    name: '恢复画面',
    group: '演出/对话',
    params: [['token', '要结束的黑屏事务标识']],
    desc: '结束配对的黑屏事务；token 不匹配时拒绝执行。',
    origin: '0x76 收尾语义',
  },
  {
    kind: 'ditherScreen',
    icon: '▦',
    name: '逐像素渐变',
    group: '演出/对话',
    params: [['ms', '总时长(可选)']],
    desc: '将上一帧按固定相位逐像素揭示为当前世界画面。',
    origin: '0x73',
  },
  {
    kind: 'shakeScreen',
    icon: '📳',
    name: '震动屏幕',
    group: '演出/对话',
    params: [
      ['frames', '持续帧数'],
      ['level', '震动强度'],
    ],
    desc: '按帧数和强度震动世界画面。',
    origin: '0x35',
  },
  {
    kind: 'setScreenWave',
    icon: '🌊',
    name: '设置屏幕波动',
    group: '演出/对话',
    params: [
      ['level', '当前波动强度'],
      ['progression', '每帧强度变化量'],
    ],
    desc: '设置持续的水波形画面偏移；状态随世界存档。',
    origin: '0x71',
  },
  {
    kind: 'playVideo',
    icon: '🎬',
    name: '播放视频',
    group: '演出/对话',
    params: [['asset', '视频 AssetId']],
    desc: '播放工程视频并阻塞脚本，直到播放完成或玩家跳过。',
  },
  {
    kind: 'playFrameAnimation',
    icon: '🎞',
    name: '播放帧动画',
    group: '演出/对话',
    params: [
      ['asset', '真彩帧动画 AssetId'],
      ['startFrame/endFrame', '闭合帧区间(可选)'],
      ['frameRate', '覆盖容器逐帧速度(可选)'],
    ],
    desc: '播放工程内真彩帧动画；可截取帧区间并覆盖播放速度。',
  },
  {
    kind: 'wait',
    icon: '⏱',
    name: '等待',
    group: '演出/对话',
    params: [['ms', '毫秒']],
    desc: '脚本暂停 N 毫秒。',
    origin: '0x0A 系延时',
  },
  // 流程/存档
  {
    kind: 'loadLastSave',
    icon: '📂',
    name: '读最近档',
    group: '流程/存档',
    params: [],
    desc: '读时间最新的存档(auto/quick/manual);无档重开。',
    origin: '0x4E',
  },
  {
    kind: 'gameOver',
    icon: '💀',
    name: '战败流程',
    group: '流程/存档',
    params: [],
    desc: '渐红 +「胜败乃兵家常事也」+ 读最近档。',
    origin: 'GameOver 枢纽段',
  },
  {
    kind: 'quitToTitle',
    icon: '🏁',
    name: '返回标题画面',
    group: '流程/存档',
    params: [['videos', '返回前依次播放的视频(可选)']],
    desc: '结束当前流程，可先播放结局视频，再返回标题画面。',
    origin: '0xA0',
  },
  // 队伍/场景
  {
    kind: 'teleportParty',
    icon: '📍',
    name: '队伍瞬移',
    group: '队伍/场景',
    params: [
      ['pos', '目标格'],
      ['facing', '朝向(可选)'],
    ],
    desc: '场景内瞬移(不换场景)。',
    origin: '0x46',
  },
  {
    kind: 'loadScene',
    icon: '🚪',
    name: '切场景',
    group: '队伍/场景',
    params: [
      ['scene', '目标场景 id'],
      ['entryId', '命名落点(可选)'],
      ['pos', '临时坐标(与命名落点互斥)'],
      ['facing', '朝向'],
      ['transition', 'modern/source 转场时序(可选)'],
    ],
    desc: '门传送/剧情转场；可用目标场景默认落点、命名落点或一次性坐标。',
    origin: '0x59(+0x46+0x50 折叠)',
  },
  {
    kind: 'setPartyFacing',
    icon: '🧭',
    name: '队伍转向',
    group: '队伍/场景',
    params: [
      ['facing', '四向'],
      ['gesture', '姿势帧(0=站立)'],
      ['member', '队员序(0=队长)'],
    ],
    desc: '转向 + 可选脚本姿势(演出用)。',
    origin: '0x15',
  },
  {
    kind: 'setFollowers',
    icon: '👥',
    name: '设置编外跟随者',
    group: '队伍/场景',
    params: [['sprites', '跟随者精灵 id 列表；空数组=清除']],
    desc: '替换队伍后方的编外跟随者，跨场景持续并随存档。',
    origin: '0x98',
  },
  {
    kind: 'setSceneMapOverride',
    icon: '🗺',
    name: '更换场景地图',
    group: '队伍/场景',
    params: [
      ['scene', '目标场景 id(缺省当前场景)'],
      ['mapId', '替换后的地图 id'],
    ],
    desc: '持久替换场景所用地图；目标为当前场景时立即重载。',
    origin: '0x99',
  },
  // 实体
  {
    kind: 'setEntityState',
    icon: '👁',
    name: '实体显隐/状态',
    group: '实体',
    params: [
      ['target', '场景 id + 实体 id'],
      ['state', '≤0 隐藏 / 1 可走 / ≥2 挡路'],
    ],
    desc: '控制在场与碰撞;宝箱开盖/尸体消失等。',
    origin: '0x49',
  },
  {
    kind: 'setMultiEntityState',
    icon: '👁',
    name: '批量设置实体状态',
    group: '实体',
    params: [
      ['targets', '场景 + 实体地址列表'],
      ['state', '≤0 隐藏 / 1 可走 / ≥2 挡路'],
    ],
    desc: '把多个稳定实体地址一次设为相同显隐和碰撞状态。',
    origin: '0x9A',
  },
  {
    kind: 'setEntityPos',
    icon: '📍',
    name: '设置实体位置',
    group: '实体',
    params: [
      ['target', '场景 id + 实体 id'],
      ['pos', '绝对目标格'],
    ],
    desc: '持久设置实体的绝对格位置，并同步当前活体。',
    origin: '0x13',
  },
  {
    kind: 'setEntityPosRelParty',
    icon: '📍',
    name: '实体相对队伍定位',
    group: '实体',
    params: [
      ['target', '场景 id + 实体 id'],
      ['dcol/drow', '相对队伍的格偏移'],
    ],
    desc: '把实体持久摆到队伍当前位置的相对格。',
    origin: '0x12',
  },
  {
    kind: 'setEntityLayer',
    icon: '📐',
    name: '设置实体图层',
    group: '实体',
    params: [
      ['target', '场景 id + 实体 id'],
      ['layer', '参与深度排序的实体层号'],
    ],
    desc: '设置实体的附加深度层，并随世界存档。',
    origin: '0x7E',
  },
  {
    kind: 'setEntityFacing',
    icon: '🧭',
    name: '实体转向',
    group: '实体',
    params: [
      ['target', '场景 id + 实体 id'],
      ['facing', '四向'],
    ],
    desc: 'NPC 转身。',
    origin: '0x0F/0x16',
  },
  {
    kind: 'setEntityFrame',
    icon: '🖼',
    name: '实体定帧',
    group: '实体',
    params: [
      ['target', '场景 id + 实体 id'],
      ['frame', '帧偏移'],
    ],
    desc: '演出定格(宝箱开盖帧等);覆盖优先于行走帧。',
    origin: '0x14/0x0F',
  },
  {
    kind: 'playEntityAction',
    icon: '▶️',
    name: '播放预制动作',
    group: '实体',
    params: [
      ['target', '场景 id + 实体 id'],
      ['sprite/action', '精灵定义 id + 稳定 ActionId'],
      ['loop', '单次 / 循环'],
      ['startAtMs', '可选起始相位'],
      ['wait', '单次动作是否阻塞脚本'],
    ],
    desc: '播放精灵库中集中定义的动作；场景脚本只保存动作引用和播放策略。',
  },
  {
    kind: 'stopEntityAction',
    icon: '⏹️',
    name: '停止预制动作',
    group: '实体',
    params: [
      ['target', '场景 id + 实体 id'],
      ['reset', '是否从头恢复页面默认动作'],
    ],
    desc: '停止剧情临时动作，并按当前场景页决定是否恢复默认动作。',
  },
  {
    kind: 'setActorSprite',
    icon: '👤',
    name: '换角色精灵',
    group: '实体',
    params: [
      ['actor', '角色 id'],
      ['sprite', '精灵 id'],
    ],
    desc: '大世界换装(练武/疯跑);持续到下次显式切换。',
    origin: '0x65',
  },
  {
    kind: 'setActorAppearance',
    icon: '🎭',
    name: '更换角色形象',
    group: '实体',
    params: [
      ['actor', '角色 id'],
      ['spriteId', '大世界精灵 id(可选)'],
      ['portrait', '头像 AssetId(可选)'],
      ['battleSprite', '战斗精灵 id(可选)'],
    ],
    desc: '持久修改角色的大世界、头像或战斗形象；一条指令至少修改一个维度。',
    origin: '0x1A',
  },
  {
    kind: 'vanishEntity',
    icon: '💨',
    name: '实体消失重现',
    group: '实体',
    params: [
      ['target', '场景 + 实体地址(缺省=触发者)'],
      ['seconds', '重现秒数(缺省不重现)'],
    ],
    desc: '野怪战败重生窗;临时态不进存档。',
    origin: 'B8 拆解',
  },
  // 世界状态
  {
    kind: 'giveItem',
    icon: '🎁',
    name: '给物品',
    group: '世界状态',
    params: [
      ['itemId', '物品 id'],
      ['count', '数量(缺省 1)'],
    ],
    desc: '入背包。',
    origin: '0x27',
  },
  {
    kind: 'loseItem',
    icon: '➖',
    name: '收物品',
    group: '世界状态',
    params: [
      ['itemId', '物品 id'],
      ['count', '数量'],
    ],
    desc: '从背包扣除。',
    origin: '0x26',
  },
  {
    kind: 'giveMoney',
    icon: '💰',
    name: '增减钱',
    group: '世界状态',
    params: [['delta', '正加负减']],
    desc: '金钱变动(下限 0)。',
    origin: '0x22 系',
  },
  {
    kind: 'halveMoney',
    icon: '💸',
    name: '金钱减半',
    group: '世界状态',
    params: [],
    desc: '按执行时的当前金钱计算并扣除一半。',
    origin: '0x8F',
  },
  {
    kind: 'increaseHpMp',
    icon: '❤',
    name: '增减全队生命法力',
    group: '世界状态',
    params: [
      ['delta', '正数恢复、负数扣除'],
      ['pools', 'hp/mp/both(缺省 both)'],
    ],
    desc: '对当前全队统一增减生命、法力或两者。',
    origin: '0x1B-0x1D',
  },
  {
    kind: 'revivePartyAll',
    icon: '✨',
    name: '复活全队',
    group: '世界状态',
    params: [['tenths', '复活生命比例的十分数']],
    desc: '复活全队，生命恢复为最大值的指定十分数，并解除重毒。',
    origin: '0x22',
  },
  {
    kind: 'learnSkill',
    icon: '📖',
    name: '学会技能',
    group: '世界状态',
    params: [
      ['role', '队伍角色序号(0-based)'],
      ['skill', '技能 id'],
    ],
    desc: '让指定角色永久学会技能。',
    origin: '0x55',
  },
  {
    kind: 'unequip',
    icon: '🔓',
    name: '卸下装备',
    group: '世界状态',
    params: [
      ['role', '队伍角色序号(0-based)'],
      ['slot', '装备槽序号或 all'],
    ],
    desc: '卸下角色指定槽或全部装备，并把物品退回背包。',
    origin: '0x23',
  },
  {
    kind: 'setFlag',
    icon: '🚩',
    name: '设 flag',
    group: '世界状态',
    params: [
      ['flag', '开关名'],
      ['value', 'true/false'],
    ],
    desc: '手工剧情开关(迁移内容走 entityState)。',
  },
  {
    kind: 'setVar',
    icon: '🔢',
    name: '设变量',
    group: '世界状态',
    params: [
      ['var', '变量名'],
      ['value', '数值'],
    ],
    desc: '手工剧情数值。',
  },
  {
    kind: 'addVar',
    icon: '➕',
    name: '变量增减',
    group: '世界状态',
    params: [
      ['var', '变量名'],
      ['delta', '增量'],
    ],
    desc: '计数器(收集/次数)。',
  },
  // 音频/战斗配置
  {
    kind: 'playSound',
    icon: '🔊',
    name: '音效',
    group: '音频/战斗配置',
    params: [['asset', '音效 AssetId']],
    desc: '播一发音效。',
    origin: '0x47',
  },
  {
    kind: 'playMusic',
    icon: '🎵',
    name: '音乐',
    group: '音频/战斗配置',
    params: [['asset', '音乐 AssetId']],
    desc: '切 BGM;进场景槽曲被本指令覆盖。',
    origin: '0x43',
  },
  {
    kind: 'stopMusic',
    icon: '⏹',
    name: '停止音乐',
    group: '音频/战斗配置',
    params: [],
    desc: '显式停止当前 BGM。',
    origin: '0x43(曲号 0)/0x77',
  },
  {
    kind: 'setAmbience',
    icon: '🌗',
    name: '切氛围(昼夜)',
    group: '音频/战斗配置',
    params: [['ambience', '氛围 id(day 昼/night 夜/自定义)']],
    desc: '切全局昼夜氛围(全帧色调滤镜);跨场景持续、随存档。',
    origin: '0x53(昼)/0x54(夜)',
  },
  {
    kind: 'toggleDayNight',
    icon: '🌗',
    name: '切换昼夜',
    group: '音频/战斗配置',
    params: [['ms', '渐变时长']],
    desc: '在昼夜状态之间切换，并按给定时长完成调色渐变。',
    origin: '0x80',
  },
  // (overrideSceneBattle 已退役:战场/曲走场景属性 battleFieldId/battleMusic 或 startBattle 一次性参数,无持久覆写)
  // 走位/相机
  {
    kind: 'moveEntity',
    icon: '🚶',
    name: '实体走到',
    group: '走位/相机',
    params: [
      ['target', '场景 id + 实体 id'],
      ['to', '目标格'],
      ['speed', 'slow/normal/fast/run'],
    ],
    desc: '阻塞直线走位。',
    origin: 'NPCWalkTo 系',
  },
  {
    kind: 'stepEntity',
    icon: '👣',
    name: '实体单步',
    group: '走位/相机',
    params: [
      ['target', '场景 id + 实体 id'],
      ['dir', '方向'],
    ],
    desc: '设向+走半格(原版 NPC 步长)。',
    origin: '0x0B-0x0E',
  },
  {
    kind: 'animEntity',
    icon: '🎞',
    name: '推进 PAL 兼容实例帧',
    group: '走位/相机',
    params: [['target', '场景 id + 实体 id']],
    desc: '旧 PAL 实例脚本逐次推进一帧；新内容应优先使用“播放预制动作”。',
    origin: '0x87',
  },
  {
    kind: 'nudgeEntity',
    icon: '↔️',
    name: '实体像素位移',
    group: '走位/相机',
    params: [
      ['target', '场景 id + 实体 id'],
      ['dx/dy', '像素'],
    ],
    desc: '瞬时微调(贴合演出)。',
    origin: '0x7D/0x6C',
  },
  {
    kind: 'moveParty',
    icon: '🚶',
    name: '队伍走到',
    group: '走位/相机',
    params: [
      ['to', '目标格'],
      ['speed', '速度'],
    ],
    desc: '阻塞队伍走位(演出)。',
    origin: '0x70/0x7A/0x7B',
  },
  {
    kind: 'nudgeParty',
    icon: '👣',
    name: '队伍相对步',
    group: '走位/相机',
    params: [
      ['dx/dy', '像素(带走姿)'],
      ['layer', '层号(可选)'],
    ],
    desc: '楼梯登阶类演出碎步；第三层号会覆盖队伍遮挡层。',
    origin: '0x6E',
  },
  {
    kind: 'chasePlayer',
    icon: '🏃',
    name: '追玩家一步',
    group: '走位/相机',
    params: [
      ['range', '追逐格半径'],
      ['speed', '快慢'],
      ['floating', '追击时忽略地形与阻挡实体'],
    ],
    desc: '放 auto 里=持续追逐(野怪);数据化版本用实体 hostile 字段。',
    origin: '0x4C 拆解',
  },
  {
    kind: 'cameraPan',
    icon: '🎥',
    name: '镜头平移',
    group: '走位/相机',
    params: [
      ['dx/dy', '每帧位移'],
      ['frames', '帧数'],
    ],
    desc: '相对平移(阻塞);跨房间演出。⚠ 不许绝对回正打断。',
    origin: '0x7F',
  },
  {
    kind: 'cameraSnap',
    icon: '🎯',
    name: '镜头落定',
    group: '走位/相机',
    params: [['to', '目标格(缺省=回正跟随)']],
    desc: '绝对跳到/回正。',
    origin: '0x7F 形态',
  },
  // 战斗/商店
  {
    kind: 'startBattle',
    icon: '⚔',
    name: '开战',
    group: '战斗/商店',
    params: [
      ['enemyTeamId', '稳定敌队 id'],
      ['onLose', '败后指令(缺省 gameOver)'],
      ['onFlee', '逃后指令'],
      ['auto', '全自动(过场战)'],
      ['boss', '首领战规则(可选)'],
      ['fieldId/music', '本场战场与音乐覆盖(可选)'],
      ['choreography', '本次遭遇专属战斗演出(可选)'],
    ],
    desc: '进战斗;剧情战配 onLose 输了也继续。',
    origin: '0x30 系',
  },
  {
    kind: 'fleeBattle',
    icon: '🏳',
    name: '敌逃离',
    group: '战斗/商店',
    params: [],
    desc: '战斗演出:敌人逃走,无奖励结束。',
    origin: '0x69',
  },
  {
    kind: 'endBattle',
    icon: '🛑',
    name: '终止战斗',
    group: '战斗/商店',
    params: [['result', 'terminate/won/lost']],
    desc: '脚本裁决战斗结果(林天南撑 7 回合)。',
    origin: '0x89',
  },
  {
    kind: 'openShop',
    icon: '🏪',
    name: '商店',
    group: '战斗/商店',
    params: [
      ['shop', '商店号'],
      ['mode', 'buy/sell'],
    ],
    desc: '开买/卖界面。',
    origin: '0x32 系',
  },
  {
    kind: 'teleportOut',
    icon: '🌀',
    name: '传送出口',
    group: '战斗/商店',
    params: [['onFail', '无出口时指令(「引路蜂不灵」)']],
    desc: '引路蜂/土灵珠:跑当前场景传送出口脚本;场景没配出口走 onFail。出口本身在场景属性配。',
    origin: '0x38',
  },
  {
    kind: 'confirm',
    icon: '❓',
    name: '是/否框',
    group: '战斗/商店',
    params: [['onNo', '选「否」的指令']],
    desc: '二择;「是」继续往下。',
    origin: '0x0A',
  },
  // 定位权威(E6b)
  {
    kind: 'takeEntity',
    icon: '🔒',
    name: '接管实体',
    group: '控制流',
    params: [['target', '场景 id + 实体 id']],
    desc: '显式接管实体定位权威:其 auto 巡逻暂停,位置归本脚本控制(位移指令会隐式接管,此指令用于「先锁再演」的精细控制)。',
    origin: 'E6 新增',
  },
  {
    kind: 'releaseEntity',
    icon: '🔓',
    name: '归还实体',
    group: '控制流',
    params: [['target', '场景 + 实体地址(缺省=全部)']],
    desc: '演出中途归还实体(恢复 auto 巡逻);脚本结束会自动归还全部,不写也不泄漏。',
    origin: 'E6 新增',
  },
  // 载具/挂载(E7)
  {
    kind: 'mountParty',
    icon: '🛶',
    name: '挂载队伍',
    group: '走位/相机',
    params: [
      ['target', '载具的场景 + 实体地址'],
      ['dx/dy', '偏移(缺省 0=重叠)'],
    ],
    desc: '队伍挂上载具(位置=载具+偏移,每帧跟随);骑乘不迈步。',
    origin: '0xA1 聚拢语义',
  },
  {
    kind: 'unmountParty',
    icon: '🚶',
    name: '下载具',
    group: '走位/相机',
    params: [],
    desc: '解除挂载,位置留当下。',
  },
  {
    kind: 'setParty',
    icon: '👥',
    name: '队伍变更',
    group: '队伍/场景',
    params: [['members', '角色模板 id 有序表(站位序)']],
    desc: '把队伍变成指定阵容:在队保留原实例、reserve 搬回、新人实例化;落选进 reserve 状态不丢(D22)。',
    origin: '0x75',
  },
  {
    kind: 'ride',
    icon: '⛵',
    name: '骑行走位',
    group: '走位/相机',
    params: [
      ['target', '载具的场景 + 实体地址'],
      ['to', '目标格'],
      ['speed', '速度'],
    ],
    desc: '驱动载具走位,队伍跟随(未挂载自动挂重叠);可连发拼路线。芦苇漂/坐船/骑驴同此契约。',
    origin: '0x3F/0x44/0x97',
  },
  // 控制流
  {
    kind: 'branch',
    icon: '🔀',
    name: '条件分支',
    group: '控制流',
    params: [
      ['cond', 'flag/var/hasItem/chance/all/any/not…'],
      ['then', '成立指令'],
      ['else', '不成立指令'],
    ],
    desc: '结构化条件;可嵌套。',
    origin: 'jump-on-X 系折叠',
  },
  {
    kind: 'loop',
    icon: '🔁',
    name: '条件循环',
    group: '控制流',
    params: [
      ['mode', 'while 条件成立时循环 / until 直到条件成立'],
      ['cond', '循环条件'],
      ['body', '每轮执行的指令'],
      ['yield', '固定 worldTick'],
      ['maxIterations', '单次运行安全上限'],
    ],
    desc: '可中断的结构化条件循环；每轮让出世界 tick，并有明确迭代上限。',
  },
  {
    kind: 'callScript',
    icon: '↪',
    name: '调用子脚本',
    group: '控制流',
    params: [
      ['script', '稳定 ScriptId'],
      ['self', '显式执行实体地址(缺省继承当前)'],
    ],
    desc: '调用稳定引用的子脚本，正常结束后返回当前命令体；作者共享脚本只是其中一种目标。',
  },
  {
    kind: 'selectEntityBehavior',
    icon: '🔗',
    name: '切换实体脚本',
    group: '控制流',
    params: [
      ['target', '场景 id + 实体 id'],
      ['channel', 'trigger 触发 / auto 自动'],
      ['selection', 'inherit/disabled/use BehaviorId'],
      ['cursorHandoff', '跨行为游标映射(可选)'],
    ],
    desc: '按稳定行为 id 切换实体触发或自动脚本；不再内嵌替换脚本体。',
    origin: '0x24/0x25 的 canonical v5 表达',
  },
  {
    kind: 'selectEntityPage',
    icon: '📄',
    name: '切换实体页面',
    group: '控制流',
    params: [
      ['target', '场景 id + 实体 id'],
      ['selection', 'inherit 或 use PageId'],
    ],
    desc: '切换实体当前页面；页面统一携带资源、行为和触发配置。',
  },
  {
    kind: 'setEntityTriggerActivation',
    icon: '🖱',
    name: '设置实体触发方式',
    group: '控制流',
    params: [
      ['target', '场景 id + 实体 id'],
      ['selection', 'inherit/disabled/use 触发配置'],
      ['selection.value.on', 'interact/touch'],
      ['selection.value.range', '触发距离(可选)'],
    ],
    desc: '继承、禁用或显式设置实体的交互/接触触发方式与距离。',
    origin: '0x40 的 canonical v5 表达',
  },
  {
    kind: 'selectSceneHooks',
    icon: '📜',
    name: '切换场景脚本',
    group: '控制流',
    params: [
      ['scene', '场景 id'],
      ['selection.onEnter', '进场 hook 的 inherit/disabled/use'],
      ['selection.onTeleport', '传送出口 hook 的 inherit/disabled/use'],
    ],
    desc: '一次切换场景进场与传送出口 hook；未提供的槽保持不变。',
    origin: '0x6D 的 canonical v5 表达',
  },
  {
    kind: 'stopScript',
    icon: '⛔',
    name: '终止本次脚本',
    group: '控制流',
    params: [],
    desc: '立即结束本次脚本运行，不执行父命令体后续指令。',
    origin: '跳转臂终止语义',
  },
]
