import type { SourceEnemy, SourceEnemyObject } from '../../migrate-enemies.js'

/** Self-contained extracted-table shapes; no real data directory or translator replacement. */
export const sourceEnemy = (over: Partial<SourceEnemy> = {}): SourceEnemy => ({
  id: 1,
  idleFrames: 2,
  magicFrames: 1,
  attackFrames: 1,
  idleAnimSpeed: 1,
  actWaitFrames: 0,
  yPosOffset: 2,
  attackSound: 1,
  actionSound: 2,
  magicSound: -3,
  deathSound: 4,
  callSound: 5,
  health: 20,
  exp: 7,
  cash: 8,
  level: 2,
  magic: 9,
  magicRate: 5,
  attackEquivItem: 12,
  attackEquivItemRate: 3,
  stealItem: 13,
  stealItemCount: 0,
  attackStrength: 10,
  magicStrength: 11,
  defense: 12,
  dexterity: 13,
  fleeRate: 14,
  poisonResistance: 15,
  elemResistance: { wind: 1, thunder: 2, water: 3, fire: 4, earth: 5 },
  physicalResistance: 2,
  dualMove: 1,
  collectValue: 4,
  _name: 'Source name',
  ...over,
})
export const sourceObject = (over: Partial<SourceEnemyObject> = {}): SourceEnemyObject => ({
  objectIndex: 398,
  enemyId: 1,
  resistanceToSorcery: 3,
  scriptOnTurnStart: 0,
  scriptOnBattleEnd: 0,
  scriptOnReady: 0,
  _name: 'Object name',
  ...over,
})
