// @vitest-environment jsdom
import { describe, expect, test } from 'vitest'
import { animationId, frameEditor, framePixels } from './__tests__/frame-editor-fixture.js'

describe('Frame editor current editing workflows', () => {
  test('shift and toggle selection preserve stable frame identities and retain one selected frame', async () => {
    const f = await frameEditor()
    await f.ready()
    await f.select(2, { shiftKey: true })
    expect(f.snapshot().selected).toEqual([0, 1, 2].map((index) => `${animationId}\0${index}`))
    expect(f.counter()).toBe('3 / 3 · 已选 3')
    await f.select(1, { ctrlKey: true })
    expect(f.snapshot().selected).toEqual([0, 2].map((index) => `${animationId}\0${index}`))
    await f.select(0, { metaKey: true })
    expect(f.snapshot().selected).toEqual([`${animationId}\0${2}`])
    await f.select(2, { ctrlKey: true })
    expect(f.snapshot().selected).toEqual([`${animationId}\0${2}`])
    f.draftOnly()
  })

  test('copy and delete selected frames keep exact pixel order and undo/redo restore the same draft', async () => {
    const f = await frameEditor()
    await f.ready()
    await f.select(1, { shiftKey: true })
    await f.click('复制选中帧')
    await f.ready()
    const pixels = () => f.cards().map((card) => [...f.pixels.get(card.querySelector('canvas')!)!])
    expect(pixels()).toEqual([0, 1, 0, 1, 2].map((index) => [...framePixels[index]!]))
    const copied = f.snapshot()
    expect(copied.selected).toHaveLength(2)
    expect(copied.selected.every((id) => !id?.startsWith(`${animationId}\0`))).toBe(true)
    await f.click('删除选中帧')
    await f.ready()
    expect(pixels()).toEqual(framePixels.map((rgba) => [...rgba]))
    expect(f.counter()).toBe('3 / 3')
    await f.click('撤销帧编辑')
    await f.ready()
    expect(pixels()).toEqual([0, 1, 0, 1, 2].map((index) => [...framePixels[index]!]))
    await f.click('重做帧编辑')
    await f.ready()
    expect(pixels()).toEqual(framePixels.map((rgba) => [...rgba]))
    f.draftOnly()
  })

  test('deleting every selected frame is disabled and a new edit after undo clears redo', async () => {
    const f = await frameEditor()
    await f.ready()
    await f.select(2, { shiftKey: true })
    expect(f.button('删除选中帧').disabled).toBe(true)
    await f.click('删除选中帧')
    expect(f.latest()?.frameCount).toBe(3)
    await f.select(1)
    await f.click('复制选中帧')
    await f.click('撤销帧编辑')
    expect(f.button('重做帧编辑').disabled).toBe(false)
    await f.click('删除选中帧')
    expect(f.latest()?.frameCount).toBe(2)
    expect(f.button('重做帧编辑').disabled).toBe(true)
    f.draftOnly()
  })

  test('global FPS commits on blur while per-frame duration overrides and clearing restore the default', async () => {
    const f = await frameEditor()
    await f.ready()
    await f.number('全局帧率', '20')
    expect(f.latest()?.defaultFrameMs).toBe(40)
    await f.number('全局帧率', '20', true)
    expect(f.latest()).toMatchObject({ defaultFrameMs: 50, durationMs: 170 })
    await f.select(1)
    await f.number('当前帧时长（ms）', '95')
    expect(f.latest()?.durationMs).toBe(195)
    await f.number('当前帧时长（ms）', '')
    expect(f.latest()?.durationMs).toBe(150)
    await f.click('撤销帧编辑')
    expect(f.latest()?.durationMs).toBe(195)
    await f.click('重做帧编辑')
    expect(f.latest()?.durationMs).toBe(150)
    await f.number('全局帧率', '0', true)
    expect(f.latest()?.defaultFrameMs).toBe(50)
    f.draftOnly()
  })

  test('navigation buttons select boundary frames and undo to the initial draft clears dirty', async () => {
    const f = await frameEditor()
    await f.ready()
    await f.click('最后一帧')
    await f.click('下一帧')
    expect(f.counter()).toBe('3 / 3')
    await f.click('上一帧')
    expect(f.counter()).toBe('2 / 3')
    await f.click('第一帧')
    await f.click('上一帧')
    expect(f.counter()).toBe('1 / 3')
    await f.click('复制选中帧')
    expect(f.dirty.mock.lastCall).toEqual([true])
    await f.click('撤销帧编辑')
    expect(f.dirty.mock.lastCall).toEqual([false])
    expect(f.button('保存动画').disabled).toBe(true)
    f.draftOnly()
  })
})
